apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Python-FastAPI-demo"
  description: "python fastapi demo project with post and get api"
  annotations:
    github.com/project-slug: https://github.com/snaveen1856/python_fastapi_demo
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: "guests"
